[project]
name = "finm32500-assignments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "memory-profiler>=0.61.0",
    "pandas>=2.3.3",
    "polars>=1.35.1",
]
